### ISSUE TITLE
无法获取 Chrome 浏览器内的文字

### ISSUE THREAD

**Issue by lmk123** [lujjjh/node-selection#1]
macOS 版本：12.2.1（cpu 是 m1）
Chrome 浏览器版本：99.0.4844.84（正式版本） (arm64)
Electron 版本：17.3.1

重现步骤：

1. 运行 `yarn add node-selection`，然后运行 `$(npm bin)/electron-rebuild`
2. 将 [getSelection.js](https://github.com/lujjjh/node-selection/blob/main/example/getSelection.js) 的代码粘贴进 Electron 的主进程代码里
3. 在终端运行 `yarn electron .`

问题：

1. 第一个问题：我使用的是 Webstrom 里的终端。当运行 `yarn electron .` 之后，控制台会持续打印：`error [Error: failed to get focused element]`，但是按照预期，由于我没在 webstrom 里选中文本，所以这里应该不是报错，而是打印出空字符串。（但是当我在代码编辑区域选中文字后，控制台能正常打印出我选中的文本。）
2. 第二个问题：当我将程序从 Webstrom 切换到 chrome 浏览器后，控制台会持续打印 `error [Error: failed to get focused element]`，中间还夹杂了两条 `error [Error: failed to get selected text]`

**Comment by lujjjh** [comment]
v0.1.5 已支持 Chrome。

部分 app 对 a11y API 的支持不完善（如 WebStorm 的终端），`node-selection` 只能获取到支持 a11y API 的元素内容。

**Comment by lmk123** [comment]
已确认此问题已在 Chrome 中修复，感谢！
