### ISSUE TITLE
electron-vite-react 启动后报错

### ISSUE THREAD

**Issue by songispm** [lujjjh/node-selection#6]
Uncaught Exception:
Error: No native build was found for platform=darwin arch=arm64

<img width="533" alt="image" src="https://github.com/lujjjh/node-selection/assets/38745323/04729090-10e1-442e-b2ad-8162a1c583e4">

使用了 [electron-vite-react](https://github.com/electron-vite/electron-vite-react)
vite下需要额外的配置吗？

求助

**Comment by songispm** [comment]
试了一下这个webpack版本的 [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) 是可以的，

vite那个不行，应该是vite相关配置问题，但不知道该怎么配

**Comment by songispm** [comment]
哦知道了

```typescript
import {defineConfig} from 'vite'
import electron from 'vite-plugin-electron'
import renderer from 'vite-plugin-electron-renderer'
import react from '@vitejs/plugin-react'
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        electron([
            {
                // Main-Process entry file of the Electron App.
                entry: 'electron/main.ts',
                vite: {
                    build: {
                        rollupOptions: {
                            // Here are some C/C++ modules them can't be built properly
                            external: [
                                'node-selection',
                            ],
                        },
                    },
                },
            },
            {
                entry: 'electron/preload.ts',
                onstart(options) {
                    // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete,
                    // instead of restarting the entire Electron App.
                    options.reload()
                },
            },
        ]),
        renderer(),
    ],
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        }
    },
})
```

**Comment by lujjjh** [comment]
还没来得及看你就已经解决了。

附上 vite-plugin-electron 仓库的相关说明：[C/C++ Native](https://github.com/electron-vite/vite-plugin-electron#cc-native)。

**Comment by songispm** [comment]
额，编译打包没问题，但打出来的包，打开运行之后报错这个，大佬再帮忙给看看 @lujjjh 

<img width="556" alt="image" src="https://github.com/lujjjh/node-selection/assets/38745323/1f16e87b-e1e7-48b3-99ac-ebac5819fd22">

**Comment by songispm** [comment]
> 额，用 [electron-vite-react](https://github.com/electron-vite/electron-vite-react) 现在本地运行没问题，编译打包也没问题，但打出来的包，打开运行之后报错这个，大佬再帮忙给看看 @lujjjh
> 
> <img alt="image" width="556" src="https://user-images.githubusercontent.com/38745323/259623389-1f16e87b-e1e7-48b3-99ac-ebac5819fd22.png">

哦，把 node-gyp-build 放到项目的 devDependencies 中就好了，已解决
