### ISSUE TITLE
[请教] 有不少应用不能读取选中文本，比如 vscode / arc / warp。请教具体来说是什么原因限制了读取能力呢？

### ISSUE THREAD

**Issue by ludafa** [lujjjh/node-selection#8]
你好，我遇到了一些问题，想请教一下：

我测试了几个常用的应用：

chrome ✅
safari ✅
electron ❌
wechat ❌
zed ❌
warp ❌
飞书 ❌

操作系统：masos 14.2.1
复现代码：https://github.com/ludafa/node-selection-demo

我有些困惑为什么除了 chrome 和 Safari 都不能读取。

我参考了 [Easydict](https://github.com/tisfeng/Easydict/blob/main/Easydict/Feature/Utility/SystemUtility/EZSystemUtility.m#L66) 相关的实现，确实不太一样的逻辑。但是 easydict 以上应用都可以提取到选中文本。

想请教 node-selection 能读取这些应用中的文本吗？为什么不能读取？

**Comment by lujjjh** [comment]
你好，无障碍 API 在某些场景下读不到文本，比如：
- 有些应用考虑到性能开销，只有当屏幕阅读器工作的时候才启用无障碍 API，比如 Chrome 和 Firefox（node-selection 针对这两个应用[手动启用了无障碍 API](https://github.com/lujjjh/node-selection/blob/368dbd3d97a34e4ecfebc1152d73196cb64527a8/src/selection_mac.mm#L10)），以及你列表中提到的 Electron 应用；
- 更多的应用是没有实现无障碍 API，或者实现不完全。

通常的做法是，如果无障碍 API 读取不到文本，就降级到模拟复制快捷键，再读取剪贴板。Easydict [也是这么做的](https://github.com/tisfeng/Easydict/blob/ac5858c86e7dfdb2a18f36ddca767b3305c1b415/Easydict/Feature/EventMonitor/EZEventMonitor.m#L432-L438)。

**Comment by ludafa** [comment]
@lujjjh 非常感谢耐心讲解 🙏

但我好奇无障碍 API “好像” 有挺大的局限。那我们是不是也把模拟复制做进来会好些？有看到这个包好像是干这个的，但应该是很久没更新了 https://github.com/garimpeiro-it/node-key-sender 有更好的其他方案推荐么？

**Comment by dmitrybabich** [comment]
Hi! Is this possible to support some configuration to provide custom bundlerIdentifers,  to enable accessibility for browsers like Arc?

**Comment by jackple** [comment]
请问, 是不是可以考虑在nodejs获取到所有的mac BundleId然后传入, 修改appsManuallyEnableAx @lujjjh

**Comment by jackple** [comment]
我试了把`com.tencent.xinWeChat`加到appsManuallyEnableAx没生效...
